In [1]:
import pandas as pd
df = pd.read_csv("US_MI_deaths.csv") 
df.fillna(0, inplace=True)

In [2]:
state = ["Michigan"]
ddf = df[df.Province_State.isin(state)]
ddf

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,4/18/20,4/19/20,4/20/20,4/21/20,4/22/20,4/23/20,4/24/20,4/25/20,4/26/20,4/27/20
1236,84026001.0,US,USA,840,26001.0,Alcona,Michigan,US,44.684686,-83.595079,...,0,0,0,0,0,0,0,0,0,0
1237,84026003.0,US,USA,840,26003.0,Alger,Michigan,US,46.412929,-86.602601,...,0,0,0,0,0,0,0,0,0,0
1238,84026005.0,US,USA,840,26005.0,Allegan,Michigan,US,42.591470,-85.891029,...,0,0,0,0,0,0,1,1,1,1
1239,84026007.0,US,USA,840,26007.0,Alpena,Michigan,US,45.034777,-83.622124,...,1,1,1,1,1,1,2,2,2,2
1240,84026009.0,US,USA,840,26009.0,Antrim,Michigan,US,44.996902,-85.155031,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1318,84026165.0,US,USA,840,26165.0,Wexford,Michigan,US,44.338536,-85.577127,...,1,1,1,1,1,1,1,1,1,2
3171,84080026.0,US,USA,840,80026.0,Out of MI,Michigan,US,0.000000,0.000000,...,2,2,2,2,1,0,1,1,1,1
3223,84090026.0,US,USA,840,90026.0,Unassigned,Michigan,US,0.000000,0.000000,...,3,4,4,4,0,0,1,1,1,1
3253,84070004.0,US,USA,840,0.0,Michigan Department of Corrections (MDOC),Michigan,US,0.000000,0.000000,...,17,17,19,20,25,28,28,31,32,37
3254,84070005.0,US,USA,840,0.0,Federal Correctional Institution (FCI),Michigan,US,0.000000,0.000000,...,0,0,0,0,0,0,0,0,1,1

In [20]:
df = ddf.drop(ddf.columns[[0,1,3,4,7,8,9]], axis=1)
df

,iso3,Admin2,Province_State,Combined_Key,Population,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,...,4/18/20,4/19/20,4/20/20,4/21/20,4/22/20,4/23/20,4/24/20,4/25/20,4/26/20,4/27/20
1236,USA,Alcona,Michigan,"Alcona, Michigan, US",10405,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1237,USA,Alger,Michigan,"Alger, Michigan, US",9108,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1238,USA,Allegan,Michigan,"Allegan, Michigan, US",118081,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
1239,USA,Alpena,Michigan,"Alpena, Michigan, US",28405,0,0,0,0,0,...,1,1,1,1,1,1,2,2,2,2
1240,USA,Antrim,Michigan,"Antrim, Michigan, US",23324,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1318,USA,Wexford,Michigan,"Wexford, Michigan, US",33631,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
3171,USA,Out of MI,Michigan,"Out of MI, Michigan, US",0,0,0,0,0,0,...,2,2,2,2,1,0,1,1,1,1
3223,USA,Unassigned,Michigan,"Unassigned, Michigan, US",0,0,0,0,0,0,...,3,4,4,4,0,0,1,1,1,1
3253,USA,Michigan Department of Corrections (MDOC),Michigan,"Michigan Department of Corrections (MDOC), Mic...",0,0,0,0,0,0,...,17,17,19,20,25,28,28,31,32,37
3254,USA,Federal Correctional Institution (FCI),Michigan,"Federal Correctional Institution (FCI), Michig...",0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [12]:
SUM = df.sum(axis=0)
print(SUM.to_string())

Population    9986857
1/22/20             0
1/23/20             0
1/24/20             0
1/25/20             0
1/26/20             0
1/27/20             0
1/28/20             0
1/29/20             0
1/30/20             0
1/31/20             0
2/1/20              0
2/2/20              0
2/3/20              0
2/4/20              0
2/5/20              0
2/6/20              0
2/7/20              0
2/8/20              0
2/9/20              0
2/10/20             0
2/11/20             0
2/12/20             0
2/13/20             0
2/14/20             0
2/15/20             0
2/16/20             0
2/17/20             0
2/18/20             0
2/19/20             0
2/20/20             0
2/21/20             0
2/22/20             0
2/23/20             0
2/24/20             0
2/25/20             0
2/26/20             0
2/27/20             0
2/28/20             0
2/29/20             0
3/1/20              0
3/2/20              0
3/3/20              0
3/4/20              0
3/5/20              0
3/6/20              0
3/7/20              0
3/8/20              0
3/9/20              0
3/10/20             0
3/11/20             0
3/12/20             0
3/13/20             0
3/14/20             0
3/15/20             0
3/16/20             0
3/17/20             0
3/18/20             1
3/19/20             1
3/20/20             1
3/21/20             3
3/22/20             9
3/23/20            15
3/24/20            24
3/25/20            43
3/26/20            61
3/27/20            92
3/28/20           111
3/29/20           132
3/30/20           184
3/31/20           259
4/1/20            335
4/2/20            417
4/3/20            479
4/4/20            540
4/5/20            617
4/6/20            727
4/7/20            845
4/8/20            959
4/9/20           1076
4/10/20          1276
4/11/20          1384
4/12/20          1479
4/13/20          1602
4/14/20          1768
4/15/20          1921
4/16/20          1996
4/17/20          2227
4/18/20          2308
4/19/20          2391
4/20/20          2468
4/21/20          2575
4/22/20          2813
4/23/20          2977
4/24/20          3085
4/25/20          3155
4/26/20          3315
4/27/20          3407

In [13]:
SUM.to_csv(r'\Users\awwin/Jupyter files/A.... Stats Project/MI_Deaths(4-27).csv', index = False)

C:\Users\awwin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.